spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  h2:
    console:
      enabled: true

  datasource:
    core:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:core;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      pool-name: core-h2db-pool
      data-source-properties:
        rewriteBatchedStatements: true
